# Project information
site_name: WebCrawler
site_url: https://webcrawler.pages.dev
site_author: Vinicius
site_description: >-
  Scripts para o WebCrawler Hacker Wars

# Repository
# repo_name: HackWarsScripts/WebCrawler
# repo_url: https://github.com/HackWarsScripts/WebCrawler

# Copyright
copyright: Copyright &copy; 2024 Brazil Team

# Configuration
theme:
  language: pt-BR
  name: material
  features:
  
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    # - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: Deep Orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: Deep Orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - Inicio: index.md
  - Sobre:
    - Logs: Sobre/logs.md
    - Relatorios: Sobre/relatorios.md
    - Intercepta Transações Bancarias: Sobre/intercepta_transacoes_bancarias.md
    - Missões: Sobre/missoes.md
    - Resolver Enigmas: Sobre/resolver_enigmas.md
  - Modelos Scripts:
      - Padrão: Exemplos/Padrao.md
      - Para Internet: Exemplos/Internet.md
      - Para Hd livre: Exemplos/HD_Livre.md
      - Sequência Jregg: Exemplos/Jregg.md
  - Regras personalizadas do Webcrawler:
    - clean_logs_disabled(): Regras personalizadas/clean_logs_disabled.md
    - clean_logs_just_after_installing(): Regras personalizadas/clean_logs_just_after_installing.md
    - leave_signature(): Regras personalizadas/leave_signature.md
    - MB(), GB(), MBits(): Regras personalizadas/MB_GB_MBits.md
    - print(): Regras personalizadas/print.md
    - seconds_limit(): Regras personalizadas/seconds_limit.md
    - softwares(): Regras personalizadas/softwares.md
    - stop(): Regras personalizadas/stop.md
    - upload(): Regras personalizadas/upload.md
  